version: '2.1'
services:
  acceptance_test:
    build: .
    environment:
      APP_URL: "${APP_URL}"
      CAPYBARA_DRIVER: "${CAPYBARA_DRIVER}"
      FEATURE_SET: "${FEATURE_SET}"
      USERNAME: "${USERNAME:-guest}"
      PASSWORD: "${PASSWORD:-guest}"
    command: rake
