version: '2.1'
services:
  acceptance_test:
    build: .
    environment:
      - APP_URL
      - CAPYBARA_DRIVER
      - FEATURE_SET
      - ACCEPTAMCE_TEST_USER
      - ACCEPTAMCE_TEST_PASSWORD
    command: rake
